# Generated by Django 2.2.23 on 2021-06-02 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tg_bot', '0002_auto_20210602_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='Название очереди')),
                ('date', models.DateField(null=True, verbose_name='Дата события')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='tg_bot.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Очередь',
                'verbose_name_plural': 'Очереди',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField(default=0, verbose_name='ID пользователя в тг')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Имя пользователя в тг')),
                ('display_name', models.CharField(blank=True, default='???', max_length=32, verbose_name='Отображаемое имя пользователя')),
                ('state', models.IntegerField(choices=[(0, 'Ввод имени'), (1, 'Главное меню'), (2, 'Создание группы'), (3, 'Присоединение к группе'), (4, 'Группа'), (5, 'Создание очереди'), (6, 'Очередь')], default=0, verbose_name='Текущее состояние чата')),
                ('cur_queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tmp_users2', to='tg_bot.Queue', verbose_name='Текущая очередь')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tg_bot.Group', verbose_name='Группа')),
                ('tmp_queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tmp_users', to='tg_bot.Queue', verbose_name='Текушая очередь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddField(
            model_name='queue',
            name='users',
            field=models.ManyToManyField(blank=True, to='tg_bot.User', verbose_name='Участники очереди'),
        ),
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_group', to='tg_bot.User', verbose_name='Админ'),
        ),
    ]
