# Generated by Django 2.2.23 on 2021-06-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210604_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='nums',
            field=models.CharField(default='[]', max_length=150, verbose_name='Номера в очереди'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(choices=[(0, 'Не зарегистрирован'), (1, 'Ввод имени'), (2, 'Главное меню'), (3, 'Создание группы'), (4, 'Присоединение к группе'), (5, 'Группа'), (6, 'Создание очереди'), (7, 'Очередь')], default=0, verbose_name='Текущее состояние чата'),
        ),
    ]
